### ISSUE TITLE
Validate inputs before exporting

### ISSUE THREAD

**Issue by mdbernard** [pr-omethe-us/ChemKED-gui#6]
Gui will crash if ChemKed receives an inappropriate input. The gui should either check all numeric fields for conformity as the user fills out the fields, or when the user clicks the export button before exporting to ChemKed to prevent crashing. The skeleton for a validation check is commented out in the export method of the Content class.

**Comment by mdbernard** [comment]
Closing due to repeat issue.

**Comment by bryanwweber** [comment]
Which one is this a duplicate of?

**Comment by mdbernard** [comment]
@bryanwweber this one:

https://github.com/pr-omethe-us/ChemKED-gui/issues/9
