### ISSUE TITLE
We should validate the input to the ChemKED processor from the GUI before export

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/ChemKED-gui#9]
I think we set the `skip_validation` parameter to `True` at some point for testing, but we need to set this back to `False`. I think the problem was that we need to handle whatever errors ChemKED is throwing in the GUI code or it crashes

**Comment by bryanwweber** [comment]
Is this resolved by #12?

**Comment by mdbernard** [comment]
I believe so. You should check that the validation is working correctly on
your end before merging and closing.
